### ISSUE TITLE
add-upload-and-gallery

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/PyP#1]
## Value Proposition

**As a** User
**I need** to upload pictures
**to be able to** look at them later in a gallery

## Description

<img src="https://user-images.githubusercontent.com/98178752/168578624-759d7c01-3341-4d4a-bfd0-e526fd6771e2.png" alt="Wireframe: page with upload button and gallery" width="300">

Branch: `add-upload-and-gallery`

## Acceptance Criteria

- [ ] button click shows picture folder
- [ ] upload on submit
- [ ] uploaded pictures are shown in gallery

## Tasks

- [ ] add storybook
- [ ] add upload button
- [ ] add cloudinary
- [ ] add gallery
- [ ] add tests
- [ ] update App
- [ ] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
