### ISSUE TITLE
add-tags

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/PyP#2]
## Value Proposition

**As a** User
**I need** to determine tags for my pictures
**to be able to** remember where I took them

## Description

<img src="https://user-images.githubusercontent.com/98178752/168835545-5e8fa225-46da-4f81-8280-7c480eb5090f.png" alt="Wireframe: upload page and gallery page" width="300">

Branch: `add-tags`

## Acceptance Criteria

- [x] user chooses picture and tags on upload page
- [x] upload on submit
- [x] uploaded pictures are shown on gallery page

## Tasks

- [x] add upload page
- [x] add upload page spec
- [x] add tags input
- <del> [ ] add picture card with tags </del>  **tags are not part of the JSON response**
- [x] add gallery page
- [x] add react router
- [x] update App
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
