### ISSUE TITLE
add-tags-filter

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/PyP#4]
## Value Proposition

**As a** User
**I need** to filter my pictures by tags
**to be able to** find certain pictures easier in my gallery

## Description

<img src="https://user-images.githubusercontent.com/98178752/170866762-9e247a6e-044a-4b80-955f-0453e3cb1bed.png" alt="Wireframe: gallery page with dropdown with tags" width="300">

Branch: `add-tags-filter`

## Acceptance Criteria

- [x] dropdown on gallery page shows all tags
- [x] pictures in gallery are filtered by chosen tag
- [x] if all pictures with one tag are deleted, tag is'nt shown in dropdown anymore

## Tasks

- [x] add dropdown to pages/Gallery.js
- [x] add filter logic
- [x] add allTags state
- [x] add tags' get request
- [x] update tests
- [x] update App
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
