### ISSUE TITLE
add-success-message

### ISSUE THREAD

**Issue by Ju-Schn** [Ju-Schn/PyP#5]
## Value Proposition

**As a** User
**I need** a success message after uploading a picture
**to be able to** know, that everything worked properly

## Description

<img src="https://user-images.githubusercontent.com/98178752/170867208-af59f398-b158-496a-9c1d-e9e9932acdcc.png" alt="Wireframe: success message on successful submit" width="300">

Branch: `add-success-message`

## Acceptance Criteria

- [x] success message is shown after file is uploaded successfully
- [x] message disappears after given time

## Tasks

- [x] add react toastify
- [x] add success message
- [x] update toast styling
- [x] test on browsers: safari, mozilla firefox, chrome, edge; device: Samsung Galaxy S10
